// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CachePanel: typeof import('./src/components/CachePanel.vue')['default']
    CCComponent: typeof import('./src/components/CCComponent.vue')['default']
    CCNode: typeof import('./src/components/CCNode.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    ProfilerPanel: typeof import('./src/components/ProfilerPanel.vue')['default']
    PropItem: typeof import('./src/components/PropItem.vue')['default']
    TreePanel: typeof import('./src/components/TreePanel.vue')['default']
    UserComponent: typeof import('./src/components/UserComponent.vue')['default']
  }
}
